<x-app-layout>
    <x-slot name="header">
        <div class="flex items-center justify-between">
            <h2 class="text-xl font-semibold text-white">Architecture</h2>
            <a href="{{ route('projects.diagrams.create', $project) }}"
               class="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-sm font-medium rounded-lg transition-colors">
                <x-lucide-plus class="w-4 h-4" />
                Nouveau diagramme
            </a>
        </div>
    </x-slot>

    <div class="max-w-7xl mx-auto space-y-8">
        @if(session('success'))
            <div class="px-4 py-3 bg-emerald-500/10 border border-emerald-500/30 rounded-lg text-emerald-400 text-sm">
                {{ session('success') }}
            </div>
        @endif

        {{-- Auto-generated architecture --}}
        <div class="bg-slate-900/80 border border-slate-700/50 rounded-xl p-5">
            <div class="flex items-center justify-between mb-4">
                <h3 class="text-lg font-semibold text-white flex items-center gap-2">
                    <x-lucide-cpu class="w-5 h-5 text-blue-400" />
                    Architecture auto-générée
                </h3>
                <span class="text-xs text-slate-500">Généré depuis les modules et dépendances</span>
            </div>
            <x-charts.mermaid-diagram :source="$autoGenerated" />
        </div>

        {{-- Custom diagrams --}}
        @if($diagrams->isNotEmpty())
            <div>
                <h3 class="text-lg font-semibold text-white mb-4">Diagrammes</h3>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    @foreach($diagrams as $diagram)
                        <a href="{{ route('projects.diagrams.show', [$project, $diagram]) }}"
                           class="block bg-slate-900/80 border border-slate-700/50 rounded-xl p-5 hover:border-blue-500/50 transition-all group">
                            <div class="flex items-center justify-between mb-3">
                                <h4 class="text-white font-medium group-hover:text-blue-400 transition-colors">{{ $diagram->title }}</h4>
                                <span class="text-xs text-slate-500 font-mono">v{{ $diagram->version }}</span>
                            </div>
                            <div class="h-32 overflow-hidden rounded-lg bg-slate-800/50 p-2">
                                <pre class="text-xs text-slate-500 overflow-hidden">{{ Str::limit($diagram->mermaid_source, 300) }}</pre>
                            </div>
                        </a>
                    @endforeach
                </div>
            </div>
        @endif
    </div>
</x-app-layout>
