<x-app-layout>
    <x-slot name="header">
        <div class="flex items-center justify-between">
            <h2 class="text-xl font-semibold" style="color: var(--o-text);">Architecture</h2>
            <a href="{{ route('projects.diagrams.create', $project) }}"
               class="btn-primary">
                <x-lucide-plus class="w-4 h-4" />
                Nouveau diagramme
            </a>
        </div>
    </x-slot>

    <div class="max-w-7xl mx-auto space-y-8">
        @if(session('success'))
            <div class="px-4 py-3 bg-emerald-500/10 border border-emerald-500/30 rounded-lg text-emerald-400 text-sm">
                {{ session('success') }}
            </div>
        @endif

        {{-- Auto-generated architecture --}}
        <div class="surface p-5">
            <div class="flex items-center justify-between mb-4">
                <h3 class="text-lg font-semibold flex items-center gap-2" style="color: var(--o-text);">
                    <x-lucide-cpu class="w-5 h-5 text-blue-400" />
                    Architecture auto-générée
                </h3>
                <span class="text-xs" style="color: var(--o-text-4);">Généré depuis les modules et dépendances</span>
            </div>
            <x-charts.mermaid-diagram :source="$autoGenerated" />
        </div>

        {{-- Custom diagrams --}}
        @if($diagrams->isNotEmpty())
            <div>
                <h3 class="text-lg font-semibold mb-4" style="color: var(--o-text);">Diagrammes</h3>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    @foreach($diagrams as $diagram)
                        <a href="{{ route('projects.diagrams.show', [$project, $diagram]) }}"
                           class="block surface p-5 hover:border-blue-500/50 transition-all group">
                            <div class="flex items-center justify-between mb-3">
                                <h4 class="font-medium group-hover:text-blue-400 transition-colors" style="color: var(--o-text);">{{ $diagram->title }}</h4>
                                <span class="text-xs font-mono" style="color: var(--o-text-4);">v{{ $diagram->version }}</span>
                            </div>
                            <div class="h-32 overflow-hidden rounded-lg p-2" style="background: var(--o-surface-2);">
                                <pre class="text-xs overflow-hidden" style="color: var(--o-text-4);">{{ Str::limit($diagram->mermaid_source, 300) }}</pre>
                            </div>
                        </a>
                    @endforeach
                </div>
            </div>
        @endif
    </div>
</x-app-layout>
