<?php

namespace App\Http\Controllers;

use App\Models\Diagram;
use App\Models\DiagramVersion;
use App\Models\Project;
use App\Services\DiagramGeneratorService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class DiagramController extends Controller
{
    public function index(Project $project, DiagramGeneratorService $generator)
    {
        Gate::authorize('view', $project);

        $diagrams = $project->diagrams()->latest()->get();
        $autoGenerated = $generator->generateArchitecture($project);

        return view('pages.diagrams.index', compact('project', 'diagrams', 'autoGenerated'));
    }

    public function create(Project $project)
    {
        Gate::authorize('update', $project);

        return view('pages.diagrams.create', compact('project'));
    }

    public function store(Request $request, Project $project)
    {
        Gate::authorize('update', $project);

        $validated = $request->validate([
            'title' => ['required', 'string', 'max:255'],
            'mermaid_source' => ['required', 'string'],
        ]);

        Diagram::create([
            'project_id' => $project->id,
            'title' => $validated['title'],
            'mermaid_source' => $validated['mermaid_source'],
        ]);

        return redirect()->route('projects.diagrams.index', $project)->with('success', 'Diagramme créé.');
    }

    public function show(Project $project, Diagram $diagram)
    {
        Gate::authorize('view', $project);

        $diagram->load('versions');

        return view('pages.diagrams.show', compact('project', 'diagram'));
    }

    public function edit(Project $project, Diagram $diagram)
    {
        Gate::authorize('update', $project);

        return view('pages.diagrams.edit', compact('project', 'diagram'));
    }

    public function update(Request $request, Project $project, Diagram $diagram)
    {
        Gate::authorize('update', $project);

        $validated = $request->validate([
            'title' => ['required', 'string', 'max:255'],
            'mermaid_source' => ['required', 'string'],
        ]);

        // Snapshot version before updating
        DiagramVersion::create([
            'diagram_id' => $diagram->id,
            'mermaid_source' => $diagram->mermaid_source,
            'version' => $diagram->version,
            'changed_by' => $request->user()->id,
        ]);

        $diagram->update([
            'title' => $validated['title'],
            'mermaid_source' => $validated['mermaid_source'],
            'version' => $diagram->version + 1,
        ]);

        return redirect()->route('projects.diagrams.show', [$project, $diagram])
            ->with('success', "Diagramme mis à jour (v{$diagram->version}).");
    }

    public function destroy(Project $project, Diagram $diagram)
    {
        Gate::authorize('update', $project);

        $diagram->delete();

        return redirect()->route('projects.diagrams.index', $project)->with('success', 'Diagramme supprimé.');
    }
}
